[2018-10-09 18:53:09] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 30 seconds exceeded" at C:\xampp\htdocs\prestashop\classes\Tools.php line 1982 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Maximum execution time of 30 seconds exceeded at C:\\xampp\\htdocs\\prestashop\\classes\\Tools.php:1982)"} []
[2018-10-09 18:54:22] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 30 seconds exceeded" at C:\xampp\htdocs\prestashop\classes\Tools.php line 1982 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Maximum execution time of 30 seconds exceeded at C:\\xampp\\htdocs\\prestashop\\classes\\Tools.php:1982)"} []
[2018-10-09 18:55:01] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 30 seconds exceeded" at C:\xampp\htdocs\prestashop\classes\Tools.php line 1982 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Maximum execution time of 30 seconds exceeded at C:\\xampp\\htdocs\\prestashop\\classes\\Tools.php:1982)"} []
[2018-10-13 10:14:19] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "idn_to_ascii" from the global namespace." at C:\xampp\htdocs\prestashop\classes\Mail.php line 872 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException(code: 0): Attempted to call function \"idn_to_ascii\" from the global namespace. at C:\\xampp\\htdocs\\prestashop\\classes\\Mail.php:872)"} []
[2018-10-13 13:50:26] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "idn_to_ascii" from the global namespace." at C:\xampp\htdocs\prestashop\classes\Mail.php line 872 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException(code: 0): Attempted to call function \"idn_to_ascii\" from the global namespace. at C:\\xampp\\htdocs\\prestashop\\classes\\Mail.php:872)"} []
[2018-10-14 00:45:12] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "idn_to_ascii" from the global namespace." at C:\xampp\htdocs\prestashop\classes\Mail.php line 872 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException(code: 0): Attempted to call function \"idn_to_ascii\" from the global namespace. at C:\\xampp\\htdocs\\prestashop\\classes\\Mail.php:872)"} []
[2018-10-14 00:45:52] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 30 seconds exceeded" at C:\xampp\htdocs\prestashop\classes\db\DbPDO.php line 147 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Maximum execution time of 30 seconds exceeded at C:\\xampp\\htdocs\\prestashop\\classes\\db\\DbPDO.php:147)"} []
[2018-10-14 15:50:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "idn_to_ascii" from the global namespace." at C:\xampp\htdocs\prestashop\classes\Mail.php line 872 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException(code: 0): Attempted to call function \"idn_to_ascii\" from the global namespace. at C:\\xampp\\htdocs\\prestashop\\classes\\Mail.php:872)"} []
